package VLOS.Processo;

public enum ProcessoStatus {

    // PROCESSO_STATUS : CLASSE RESPONSAVEL POR REPRESENTAR O STATUS DE UM PROCESSO

    PRONTO,
    EXECUTANDO,
    ESPERANDO,
    CONCLUIDO;

}
