package VLOS.Memoria;


public enum BlocoStatus {

    // BLOCO_STATUS : CLASSE RESPONSAVEL POR REPRESENTAR O STATUS DE UM BLOCO EM MEMORIA

    RESERVADO_KERNEL,
    OCUPADO_KERNEL,
    LIVRE,
    OCUPADO;

}
